<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php $this->getPageTitle('|') ?>FramkMVC</title>
   <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
   <link href="/assets/css/style.css" rel="stylesheet">

   <!-- Bootstrap CSS -->

  </head>
  <body>
  	<?php require_once __DIR__ . "/menu.phtml" ?>

    <?php $this->content() ?>

    <script src="/assets/js/jquery.min.js"></script>

    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>
